@baseUrl = http://localhost:8080
@token = 

###
POST {{baseUrl}}/api/users/register
Content-Type: application/json

{
  "name": "testuser",
  "email": "lazyfox916@gmail.com",
  "password": "testpassword"
}

###

POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "email": "lazyfox916@gmail.com",
  "password": "testpassword"
}

###
GET {{baseUrl}}/api/users/
Authorization: Bearer {{token}}

###
GET {{baseUrl}}/api/users/1fcf6d10-0d95-4c5d-942f-fdc5ea8c18c1
Authorization: Bearer {{token}}